name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Output Run ID
      run: echo ${{ github.run_id }}
    - name: Output Run Number
      run: |
           NUM=${{ github.run_number }}
           echo $NUM   
    - name: Build the Docker image  
      run:  docker build -t my-image-name:$NUM .
            docker run -d -p 3000:3000 my-image-name:$NUM 

  stage:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - name: Dockerlogin  
      run: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    
                
            
      
