name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Output Run ID
      run: echo ${{ github.run_id }}
    - name: Output Run Number
      run: |
           NUM=${{ github.run_number }}
           echo $NUM   
           docker build -t react:$NUM .
  stage:
    runs-on: ubuntu-latest 
    steps:
    - uses: docker/login-action@v1
    - name: Dockerlogin
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
    - run: echo "Login Success"  
    
                
            
      
