name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: | 
          echo $build_number
          docker build . --file Dockerfile --tag my-image-name:$build_number
          docker run -d -p 3000:3000 my-image-name:$build_number

  stage: 

    runs-on: ubuntu-latest

    steps:

    - uses:
    - name: Push the docker image to docker hub        
      
