name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Output Run ID
      run: echo ${{ github.run_id }}
    - name: Output Run Number
      run: echo ${{ github.run_number }} 
    - name: Build the Docker image  
      run:  docker build . --file Dockerfile --tag my-image-name:$NUMBER
            docker run -d -p 3000:3000 my-image-name:$NUMBER

  stage:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - name: Dockerlogin  
      run: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: push the image
      run: |
            docker push ${{secrets.DOCKER_USERNAME}}/$REPO_NAME     
            
      
